language: node_js
node_js: 
- "10"
cache:
  directories:
    - "node_modules"
install:
  - "npm install"
script:
  - "npm run coverage"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: travis-ui